---
- hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Read inception variables.
      ansible.builtin.import_tasks:
        file: tasks/inception/read_inception_variables.yml

    - ansible.builtin.import_tasks:
        file: tasks/read_build_configuration.yml
      vars:
        this_host: localhost

- hosts: localhost_build_group
  gather_facts: false
  become: true

  tasks:
  - ansible.builtin.import_tasks:
      file: /root/local_ansible/inception_task.yml
