# Creates ansible/results/ips2root_server_software.csv
# tab separated with four columns: IPv4, IPv6, hostname, software
---
- hosts: root_servers
  gather_facts: false
  become: true

  tasks:
  - block:
#    - debug: 
#        msg: "{{ item.1.0 }} {{ item.1.1 }} {{ inventory_hostname }} {{ item.0.name }}"
#      loop: "{{ build_config.software | zip((network_configuration.networks.0.v4.alias | map('dirname')) | zip(network_configuration.networks.0.v6.alias | map('dirname'))) }}"

    - name: Log IPv4 -> IPv6 -> hostname -> software mapping
      ansible.builtin.lineinfile:
        path: results/ips2root_server_software.csv
        insertafter: EOF
        line: "{{ item.1.0 }}\t{{ item.1.1 }}\t{{ inventory_hostname }}\t{{ item.0.name }}"
        create: true
      loop: "{{ build_config.software | zip((network_configuration.networks.0.v4.alias | map('dirname')) | zip(network_configuration.networks.0.v6.alias | map('dirname'))) }}"

    delegate_to: localhost
    become: false
