---
- hosts: resolvers-vm
  gather_facts: false
  become: true

  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/network_provision.yml

  handlers:
    - ansible.builtin.import_tasks:
        file: handlers/network_restart.yml
