---
- hosts: servers-vm
  gather_facts: false
  become: true

  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/network_provision.yml

    - name: Making the bind-configs directory.
      ansible.builtin.file:
        path: /root/bind-configs
        state: directory

    - name: Copying the root files.
      ansible.builtin.copy:
        src: files/root-zone-basic/
        dest: /root/bind-configs

    - name: rc.local for named and ipfw init.
      ansible.builtin.copy:
        src: files/servers-rc.local
        dest: /etc/rc.local

    - name: Copy ipfw configuration.
      ansible.builtin.copy:
        src: files/servers-ipfw-long-to-short.sh
        dest: /root/servers-ipfw-long-to-short.sh
        mode: "a+x"

    - name: Install packages.
      community.general.pkgng:
        name:
          - bind916
          - wget
          - nano
          - vim
          - tmux
          - htop
          - ca_root_nss
        state: present

    - ansible.builtin.import_tasks:
        file: tasks/finish_provisioning.yml
