---
- hosts: gateway-vm
  gather_facts: false
  become: true

  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/network_provision.yml

    - name: Configure for NAT
      ansible.builtin.copy:
        src: files/rc-local-on-gateway-vm
        dest: /etc/rc.local
        mode: "u+x"

    - ansible.builtin.import_tasks:
        file: tasks/finish_provisioning.yml
