---
- hosts: resolvers-vm
  gather_facts: false
  become: true

  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/network_provision.yml

    - ansible.builtin.import_tasks:
        file: tasks/finish_provisioning.yml
