---
- hosts: resolvers-vm
  gather_facts: false
  become: true

  tasks:
    - name: Configure interfaces.
      ansible.builtin.template:
        src: templates/linux_interfaces.j2
        dest: /etc/network/interfaces

    - name: Set hostname.
      ansible.builtin.copy:
        content: "{{ inventory_hostname }}\n"
        dest: /etc/hostname

    - ansible.builtin.import_tasks:
        file: tasks/resolv.conf.yml

    - name: Provisioning done; shutting down.
      community.general.shutdown:

    - name: Wait for SSH port to disappear.
      ansible.builtin.wait_for:
        port: "{{ ansible_ssh_port }}"
        state: "stopped"
