---
- hosts: servers-vm
  gather_facts: false
  become: true

  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/network_provision.yml

    - name: Making the bind-configs directory.
      ansible.builtin.file:
        path: /root/bind-configs
        state: directory

    - name: Copying the root files.
      ansible.posix.synchronize:
        src: files/root-zone-basic/
        dest: /root/bind-configs

    - name: Copying the configuration.
      ansible.builtin.template:
        src: templates/named.conf.j2
        dest: /root/bind-configs/named.conf
      vars:
        listen_addrs: "\
          {% set output = [] %}\
          {% for n in network_configuration['networks'] %}\
          {% if n.vbox_arguments[3] == 'SERVER_INTNET' %}\
          {{ output.extend(n['v4']['alias'] | map('dirname')) }}\
          {% endif %}\
          {% endfor %}\
          {{ output }}"
        listen_addrs_6: "\
          {% set output = [] %}\
          {% for n in network_configuration['networks'] %}\
          {% if n.vbox_arguments[3] == 'SERVER_INTNET' %}\
          {{ output.extend(n['v6']['alias'] | map('dirname')) }}\
          {% endif %}\
          {% endfor %}\
          {{ output }}"

    - name: rc.local for named and ipfw init.
      ansible.builtin.copy:
        src: files/servers-rc.local
        dest: /etc/rc.local

    - name: Copy ipfw configuration.
      ansible.builtin.copy:
        src: files/servers-ipfw-long-to-short.sh
        dest: /root/servers-ipfw-long-to-short.sh
        mode: "a+x"

    - name: Restart network if needed.
      ansible.builtin.meta: flush_handlers

    - name: Activate ipfw configuration.
      ansible.builtin.shell:
        cmd: /root/servers-ipfw-long-to-short.sh

    - name: Install packages.
      community.general.pkgng:
        name:
          - bind916
          - wget
          - nano
          - vim
          - tmux
          - htop
          - ca_root_nss
        state: present

  handlers:
    - ansible.builtin.import_tasks:
        file: handlers/network_restart.yml
