---
- hosts: resolvers-vm
  gather_facts: false
  become: true

  tasks:
    - name: Configure interfaces.
      ansible.builtin.template:
        src: templates/linux_interfaces.j2
        dest: /etc/network/interfaces

    - name: Set hostname.
      ansible.builtin.template:
        src: templates/linux_hostname.j2
        dest: /etc/hostname

    - ansible.builtin.import_tasks:
        file: tasks/resolv.conf.yml
