---
- hosts: resolvers-vm
  gather_subset: "!all,!min,distribution_release"
  become: true

  tasks:
    - name: Add the build software as hosts.
      ansible.builtin.add_host:
        name: "{{ item.key }}"
        groups: build_group
        url: "{{ item.value['url'] }}"
        make_str: "{{ build_config['templates'][item.value['make_str']] }}"
        host_name: "{{ item.key }}"
        files_copy: "{{ 'files_copy' in item.value and item.value['files_copy'] | default([]) }}"
      loop: "{{ build_config['software'] | dict2items }}"

    - name: Make sure the needed directories are there.
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ BUILD_SOURCE_DIR }}"
        - "{{ BUILD_TARGET_DIR }}"

    - ansible.builtin.import_tasks:
        file: tasks/install_generic_packages_apt.yml

    - name: Add CZ.nic apt key.
      ansible.builtin.get_url:
        url: https://deb.knot-dns.cz/apt.gpg
        dest: /etc/apt/trusted.gpg.d/knot.gpg

    - name: Add CZ.nic repository.
      ansible.builtin.apt_repository:
        repo: "deb https://deb.knot-dns.cz/knot-latest/ {{ ansible_distribution_release }} main"
        filename: knot-latest.list
        state: present
        update_cache: yes

    - name: Install VM specific packages.
      ansible.builtin.apt:
        pkg:
          - build-essential
          - libssl-dev
          - libcap-dev
          - python3-ply
          - dnsutils
          - pkg-config
          - libuv1-dev
          - libcmocka-dev
          - libluajit-5.1-dev
          - liblua5.1-0-dev
          - autoconf
          - libtool
          - liburcu-dev
          - libgnutls28-dev
          - libedit-dev
          - libldns-dev
          - libexpat-dev
          - libboost-dev
          - libboost-system-dev
          - libboost-thread-dev
          - libboost-context-dev
          - libknot-dev
          - liblmdb-dev
          - ninja-build
        state: present
        update_cache: yes

    - name: Install meson for Python3.
      ansible.builtin.pip:
        name: meson
        executable: pip3

- hosts: build_group
  strategy: free
  gather_facts: false
  become: true
  vars:
    on_host: resolvers-vm
  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/compile_resolver.yml
