---
# This playbook configures the gateway-vm to do loadbalancing;
# All queries for the a root (a.some-servers.p53, 172.21.101.1), will
# be round-robin load-balanced over the 12 other roots
- hosts: gateway-vm
  gather_facts: false
  become: true

  tasks:
    - name: Copy loadbalance configuration.
      ansible.builtin.template:
        src: templates/full_loadbalance_file.json.j2
        dest: /etc/nftlb.json
    
    - name: Install nftlb package
      ansible.builtin.apt:
        pkg:
          - nftlb
          - curl
        state: present
        update_cache: true
    
    - name: Override startup service to use configuration
      ansible.builtin.copy:
        src: files/loadbalancer/systemd.nftlb.service
        dest: /lib/systemd/system/nftlb.service

    - name: Restart the service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: nftlb
