---
- hosts: gateway-vm
  gather_facts: false
  become: true

  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/install_generic_packages.yml

    - name: Install VM specific packages.
      ansible.builtin.apt:
        pkg:
          - tcpdump
          - dtach
          - iptables
        state: present
        update_cache: yes

    - name: Install tcpdump service file
      ansible.builtin.copy:
        src: files/gateway-vm/tcpdumpd.service
        dest: /etc/systemd/system

