---
- hosts: resolvers-vm
  gather_subset: "!all,!min,distribution_release"
  become: true

  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/read_build_configuration.yml

    - ansible.builtin.import_tasks:
        file: tasks/install_generic_packages.yml

    - name: Install VM specific packages (part I).
      ansible.builtin.apt:
        pkg:
          - lsb-release
          - ca-certificates
          - python3-pip
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Add CZ.nic apt key.
      ansible.builtin.get_url:
        url: https://deb.knot-dns.cz/apt.gpg
        dest: /etc/apt/trusted.gpg.d/knot.gpg

    - name: Add CZ.nic repository.
      ansible.builtin.apt_repository:
        repo: "deb https://deb.knot-dns.cz/knot-latest/ {{ ansible_distribution_release }} main"
        filename: knot-latest.list
        state: present
        update_cache: yes

    - name: Install VM specific packages (part II).
      ansible.builtin.apt:
        pkg:
          - build-essential
          - libssl-dev
          - libcap-dev
          - python3-ply
          - pkg-config
          - libuv1-dev
          - libcmocka-dev
          - libluajit-5.1-dev
          - liblua5.1-0-dev
          - autoconf
          - libtool
          - liburcu-dev
          - libgnutls28-dev
          - libedit-dev
          - libldns-dev
          - libexpat-dev
          - libboost-dev
          - libboost-system-dev
          - libboost-thread-dev
          - libboost-context-dev
          - libknot-dev
          - liblmdb-dev
          - ninja-build
          - libboost-test-dev
        state: present
        update_cache: yes

    - name: Install meson for Python3.
      ansible.builtin.pip:
        name: meson
        executable: pip3

- hosts: build_group
  gather_facts: false
  become: true
  vars:
    on_host: resolvers-vm
  tasks:
    - ansible.builtin.import_tasks:
        file: tasks/compile_software.yml
