---
- block:
  - name: Check for inception file.
    find:
      paths: /root/local_ansible
      patterns: inception_variables.yml
      file_type: file
      recurse: false
    register: inception_file

  - name: Read inception variables.
    include_vars:
      file: /root/local_ansible/inception_variables.yml
    when: inception_file.files != []

  delegate_to: localhost
