---
- name: Create ports directory for NSD 4.1.3
  ansible.builtin.file:
    path: /usr/old/nsd413
    state: directory
    mode: '0755'

- name: Sparse checkout ports and build NSD 4.1.3 from it
  ansible.builtin.shell:
    chdir: /usr/old/nsd413
    cmd: |
      git init
      git remote add ports https://git.FreeBSD.org/ports.git
      git sparse-checkout set "dns/nsd" "Mk" "Keywords" "Templates" "ports-mgmt/pkg" "devel/libevent"
      git pull --depth=1 ports a6dcae5a9076ab84f7a232bf3a7e4d870d10ef59
      cd dns/nsd
      git checkout a6dcae5a9076ab84f7a232bf3a7e4d870d10ef59
      env VALID_CATEGORIES=ipv6 OPTIONS_SET=ROOT_SERVER BATCH=on make install-missing-packages
      env VALID_CATEGORIES=ipv6 OPTIONS_SET=ROOT_SERVER BATCH=on make build
