---
- hosts: gateway-vm
  gather_facts: false
  become: true

  tasks:
    - name: Start tcpdump service, if not started
      ansible.builtin.find:
        paths: /var/log/tcpdumpd
        patterns: '*.pcap'
      register: files

    - debug:
        msg: '{{ (files.files | sort(attribute="mtime", reverse=true) | first).path if files.files|count > 0 else "cannot find any file" }}'

    - name: Copy latest packet capture, if found
      ansible.builtin.fetch:
        src: '{{ (files.files | sort(attribute="mtime", reverse=true) | first).path }}'
        dest: 'captures/{{ (files.files | sort(attribute="mtime", reverse=true) | first).path | basename }}'
        flat: true
      when: files.files|count > 0

