---
- name: Install generic packages.
  ansible.builtin.apt:
    pkg:
      - tar
      - wget
      - vim
      - tmux
      - htop
      - lsb-release
      - ca-certificates
      - python3-pip
      - apt-transport-https
    state: present
    update_cache: yes
