---
- name: Use default task variables if not specified.
  ansible.builtin.set_fact:
    pip_executable: "{{ whichpip | default('pip3') }}"
    pip_version: "{{ pipversion | default(false) }}"
    system_ansible: "{{ use_system_ansible | default(true) }}"

- ansible.builtin.include_tasks:
    file: "tasks/install_generic_packages_{{ system.package }}.yml"
