---
- name: (linux) Install packages for building.
  ansible.builtin.apt:
    pkg:
      - build-essential
      - autoconf
      - libtool
      - pkg-config
      - libevent-dev
      - libssl-dev
      - python-ply
      - python3-ply
      - libmaxminddb-dev
      - libjson-c-dev
      - protobuf-c-compiler
      - libprotobuf-c-dev
      - libfstrm-dev
      - libuv1-dev
      - libcap-dev
      - libgnutls28-dev
      - liburcu-dev
      - liblmdb-dev
      - libedit-dev
    state: present
    update_cache: yes
  when: network_configuration.system in ['linux', 'ubuntu']

- name: (FreeBSD) Install packages for building.
  community.general.pkgng:
    name: []
    state: present
  when: network_configuration.system == 'freebsd'

- name: (NetBSD) Install packages for building.
  community.general.pkgin:
    name: []
    state: present
  when: network_configuration.system == 'netbsd'

- name: (CentOS) Install packages for building.
  ansible.builtin.yum:
    name: []
    state: present
  when: network_configuration.system == 'centos'

- name: Unknown system; fail the playbook.
  ansible.builtin.fail:
    msg: "Unknown system! Cannot install packages!"
  when: "network_configuration.system not in ['linux', 'ubuntu', 'freebsd', 'netbsd', 'centos']"
