---
- name: (FreeBSD) Install generic packages.
  community.general.pkgng:
    name:
      - gtar
      - tree
      - wget
      - vim
      - tmux
      - htop
      - rsync
      - bind-tools
    state: present

- name: (FreeBSD) Install system ansible.
  community.general.pkgng:
    name:
      - py39-ansible
    state: present
  when: system_ansible is true

- block:
  - name: (FreeBSD) Remove unwanted packages.
    community.general.pkgng:
      name:
        - py39-ansible
      state: absent

  - name: (FreeBSD) Get latest pip.
    ansible.builtin.pip:
      name: "{{ 'pip=={}'.format(pip_version) if pip_version else 'pip' }}"
      state: "{{ 'present' if pip_version else 'latest' }}"
      executable: "{{ pip_executable }}"

  - name: (FreeBSD) Install Ansible with pip.
    ansible.builtin.pip:
      name: ansible==4.2.0
      executable: "{{ pip_executable }}"
  when: system_ansible is false
