---
  - name: (Rc.d) Set rc.local.
    ansible.builtin.template:
      src: "{{ rc_template }}"
      dest: /etc/rc.local
      owner: root
      mode: "u+x"

  - name: (Systemd) Source rc.local.
    ansible.builtin.shell:
      cmd: ". /etc/rc.local"
