---
- name: CentOS network configuration.
  block:
  - name: (CentOS) Disable SELinux.
    ansible.posix.selinux:
      state: disabled

  - name: (CentOS) Configure interfaces.
    ansible.builtin.template:
      src: templates/centos_ifcfg.j2
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{item.name}}"
    loop: "{{ network_configuration.networks }}"

  - name: (CentOS) Configure IPv4 routing.
    ansible.builtin.template:
      src: templates/centos_route.j2
      dest: "/etc/sysconfig/network-scripts/route-{{item.name}}"
    loop: "{{ network_configuration.networks }}"

  - name: (CentOS) Configure IPv6 routing.
    ansible.builtin.template:
      src: templates/centos_route6.j2
      dest: "/etc/sysconfig/network-scripts/route6-{{item.name}}"
    loop: "{{ network_configuration.networks }}"

  - ansible.builtin.include_tasks:
      file: tasks/network_restart_centos.yml

  - name: (CentoOS) Set rc.local.
    ansible.builtin.template:
      src: templates/rc.local_linux.j2
      dest: /etc/rc.local
      owner: root
      group: root
      mode: "u+x"

  - name: (CentoOS) Source rc.local.
    ansible.builtin.shell:
      cmd: ". /etc/rc.local"
