---
- name: Ubuntu network configuration.
  block:
  - name: (Ubuntu) Configure interfaces.
    ansible.builtin.template:
      src: templates/ubuntu_netplan.j2
      dest: /etc/netplan/01-netcfg.yaml
    notify: restart_network

  - name: (Ubuntu) Check hostname.
    ansible.builtin.shell:
      cmd: "hostname"
    register: hostname_out

  - name: (Ubuntu) Set hostname.
    ansible.builtin.shell:
      cmd: "hostname {{ inventory_hostname }}"
    when: hostname_out.stdout != inventory_hostname

  - ansible.builtin.include_tasks:
      file: tasks/resolv.conf.yml
