---
- name: CentOS network configuration.
  block:
  - name: (CentOS) Configure interfaces.
    ansible.builtin.template:
      src: templates/centos_ifcfg.j2
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{item.name}}"
    loop: "{{ network_configuration.networks }}"
    notify: restart_network

  - name: (CentOS) Configure IPv4 routing.
    ansible.builtin.template:
      src: templates/centos_route.j2
      dest: "/etc/sysconfig/network-scripts/route-{{item.name}}"
    loop: "{{ network_configuration.networks }}"
    notify: restart_network

  - name: (CentOS) Configure IPv6 routing.
    ansible.builtin.template:
      src: templates/centos_route6.j2
      dest: "/etc/sysconfig/network-scripts/route6-{{item.name}}"
    loop: "{{ network_configuration.networks }}"
    notify: restart_network

      #- name: (CentOS) Disable NetworkManager.
      #  ansible.builtin.systemd:
      #    name: NetworkManager
      #    enabled: false

  - ansible.builtin.include_tasks:
      file: tasks/resolv.conf.yml
