---
- ansible.builtin.include_tasks:
    file: "tasks/network_provision_{{ network_configuration.system }}.yml"
  when: network_configuration.system in ['linux', 'ubuntu', 'freebsd', 'netbsd', 'centos']

- name: Unknown system; fail the playbook.
  ansible.builtin.fail:
    msg: "Unknown system! Cannot configure network!"
  when: "network_configuration.system not in ['linux', 'ubuntu', 'freebsd', 'netbsd', 'centos']"
