---
- name: Linux configuration
  block:
  - name: (linux) Configure interfaces.
    ansible.builtin.template:
      src: templates/linux_interfaces.j2
      dest: /etc/network/interfaces

  - name: (linux) Set hostname.
    ansible.builtin.copy:
      content: "{{ inventory_hostname }}\n"
      dest: /etc/hostname

  - ansible.builtin.import_tasks:
      file: tasks/resolv.conf.yml
  when: network_configuration.system == 'linux'

- name: FreeBSD configuration
  block:
  - name: (FreeBSD) Configure interfaces (in rc.conf)
    ansible.builtin.template:
      src: templates/freebsd_rc.conf.j2
      dest: /etc/rc.conf

  - ansible.builtin.import_tasks:
      file: tasks/resolv.conf.yml

  - name: (FreeBSD) Making boot faster; always autoboot.
    ansible.builtin.copy:
      content: 'autoboot_delay="-1"'
      dest: /boot/loader.conf

  when: network_configuration.system == 'freebsd'
