---
- name: Per software configuration tasks.
  delegate_to: "{{ on_host }}"
  vars:
    this_source_dir: "{{ BUILD_SOURCE_DIR }}/{{ software_name }}"
    this_target_dir: "{{ BUILD_TARGET_DIR }}/{{ software_name }}"
  block:
  - name: Check if we already built the source.
    ansible.builtin.stat:
      path: "{{ this_target_dir }}/.compiled.this"
    register: software_compiled

  - name: Configure compiled software
    when: software_compiled.stat.exists
    block:
    - name: Configure BIND
      when: software_sname == 'bind'
      ansible.builtin.meta: noop

    - name: Configure Unbound
      when: software_sname == 'unbound'
      block: 
      - name: Start resolver (if not running)
        ansible.builtin.shell:
          cmd: "PATH={{ this_target_dir }}/bin:{{ this_target_dir }}/sbin:$PATH unbound-control start"
          chdir: "{{ this_target_dir }}"

      - name: Do query
        ansible.builtin.shell:
          cmd: dig @{{ listen_ipv4 }} example.com +timeout=5

