---
- name: Add the build software as hosts.
  ansible.builtin.add_host:
    name: "{{ item.key }}"
    groups: build_group
    url: "{{ item.value['url'] }}"
    make_str: "{{ build_config['templates'][item.value['make_str']] }}"
    files_copy: "{{ ('files_copy' in item.value and item.value['files_copy']) or [] }}"
    # This is needed when delegate_to is used to preserve the hostname
    # since Ansible uses the delegate_to hostname as the inventory_hostname
    host_name: "{{ item.key }}"
  loop: "{{ build_config['software'] | dict2items }}"

- name: Make sure the needed directories are there.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BUILD_SOURCE_DIR }}"
    - "{{ BUILD_TARGET_DIR }}"
