---
- name: Check required variables for this task.
  assert:
    that:
      - software_source_dir is defined
      - software_target_dir is defined
      - software_build_config is defined
    fail_msg: "Not all required variables are defined!"

- name: Add the build software as hosts.
  add_host:
    name: "{{ item.key }}"
    groups: "{{ inventory_hostname | replace('-', '_') }}_build_group"
    url: "{{ item.value['url'] }}"
    make_str: "{{ software_build_config['templates'][item.value['make_str']] }}"
    files_copy: "{{ ('files_copy' in item.value and item.value['files_copy']) or [] }}"
    # This is needed when delegate_to is used to preserve the hostname
    # since Ansible uses the delegate_to hostname as the inventory_hostname
    software_name: "{{ item.key }}"
  loop: "{{ software_build_config['software'] | dict2items }}"

- name: Make sure the needed directories are there.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ software_source_dir }}"
    - "{{ software_target_dir }}"
