---
- name: Set resolv.conf for linux.
  block:
  - name: Try writing resolv.conf.
    ansible.builtin.copy:
      src: ../files/resolv-with-8844
      dest: /etc/resolv.conf
      attr: "+i"
  rescue:
    - name: Make sure the file is mutable.
      ansible.builtin.file:
        path: /etc/resolv.conf
        attr: "-i"

    - name: Try writing resolv.conf (again).
      ansible.builtin.copy:
        src: ../files/resolv-with-8844
        dest: /etc/resolv.conf
        attr: "+i"
  when: network_configuration.system == 'linux'

- name: Set resolv.conf for freebsd.
  block:
  - name: Write resolv.conf.
    ansible.builtin.copy:
        src: ../files/resolv-with-8844
        dest: /etc/resolv.conf
  when: network_configuration.system == 'freebsd'
