---
- name: Set resolv.conf.
  block:
  - name: Try writing resolv.conf.
    ansible.builtin.copy:
      src: ../files/resolv-with-8844
      dest: /etc/resolv.conf
      attr: "+i"
  rescue:
    - name: Make sure the file is mutable.
      ansible.builtin.file:
        path: /etc/resolv.conf
        attr: "-i"

    - name: Try writing resolv.conf (again).
      ansible.builtin.copy:
        src: ../files/resolv-with-8844
        dest: /etc/resolv.conf
        attr: "+i"
