---
- name: Set the zones for scenario 2
  ansible.builtin.set_fact:
    zone_cfg:
      - [".", "{{ ZONE_DIR }}/2/root.zone"]
      - ["p53.", "{{ ZONE_DIR }}/2/p53.zone"]
      - ["some-servers.p53.", "{{ ZONE_DIR }}/2/some-servers.p53.zone"]
