---
- name: Set the zones for scenario 6 with real IPs
  ansible.builtin.set_fact:
    zone_cfg:
      - [".", "{{ ZONE_DIR }}/5.6.1-root"]
  when: do_realips is not defined or do_realips is true

- name: Set the zones for scenario 6 without real IPs
  ansible.builtin.set_fact:
    zone_cfg:
      - [".", "{{ ZONE_DIR }}/9.6.1-root"]
  when: do_realips is defined and do_realips is false

#- name: Set the zones for scenario 6 without real IPs
#  ansible.builtin.set_fact:
#    zone_cfg:
#      - [".", "{{ ZONE_DIR }}/6/root_.zone"]
#  when: do_realips is defined and do_realips is false
