#!/bin/sh

# Add delays
tc qdisc add dev enp0s8 root netem delay 1200ms
tc qdisc add dev enp0s9 root netem delay 1000ms
tc qdisc add dev enp0s10 root netem delay 800ms
tc qdisc add dev enp0s16 root netem delay 600ms
tc qdisc add dev enp0s17 root netem delay 400ms
tc qdisc add dev enp0s18 root netem delay 200ms
# Nothing for enp0s19

# Start named
cd /root/bind-configs && /root/Target/bind-9.12.3/sbin/named -c named.conf